name: Build

on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    runs-on: windows-latest
    name: Build
    steps:
    - uses: actions/checkout@v2

    - name: Setting up cache
      uses: actions/cache@v1
      id: cache
      with:
        path: ./dependencies
        key: ${{ runner.os }}-v1

    - name: Install dependencies
      run: |
        mkdir .\dependencies
        mkdir .\dependencies\ahk
        mkdir .\dependencies\magick
        curl.exe https://www.autohotkey.com/download/ahk.zip -L -o dep_ahk.zip
        7z e dep_ahk.zip -odependencies\ahk
        curl.exe https://imagemagick.org/download/binaries/ImageMagick-7.0.10-14-portable-Q16-x64.zip -L -o dep_magick.zip
        7z e dep_magick.zip -odependencies\magick

    - name: Build app
      run: |
        npm run build:icon
        npm run build:app

    - name: Create an archive
      working-directory: dist
      run: |
        7z a shutdown-prompt-gui.7z shutdown-prompt-gui.exe

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}

    - name: Upload release asset
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/shutdown-prompt-gui.7z
        asset_name: shutdown-prompt-gui_${{ github.ref }}.7z
        asset_content_type: application/x-7z-compressed
